### ISSUE TITLE
Any info about this project？

### ISSUE THREAD

**Issue by chengwei0427** [ZikangYuan/SDV-LOAM#1]
Any info about this project？

Project description？

Related publications？

**Comment by ZikangYuan** [comment]
Thanks for your interest in our project. Now I have added a brief description of this project in readme.txt. I am sorry that I can't disclose the implementation details of the method of this project before publication. But I would immediately provide the corresponding description of details and release the source code after the publication of paper.

**Comment by chengwei0427** [comment]
Thank you for reply. 

I'll give a star on this project.

Lastly, wish get good feedback on your paper.

**Comment by chengwei0427** [comment]
Any new progress?

**Comment by ZikangYuan** [comment]
The vision module of SDV-LOAM has been released, and the full code would be released soon.
