### ISSUE TITLE
sensor文件夹里面txt文件的参数含义

### ISSUE THREAD

**Issue by OpenAskDragon** [ZikangYuan/SDV-LOAM#10]
您好，非常感谢您的工作，这是您sensor文件夹里面的00.txt，每一个数值都没有注释，不知能否告知一下每一个的含义是什么
718.856 718.856 607.1928 185.2157
4.276802385584e-04 -9.999672484946e-01 -8.084491683471e-03 -1.198459927713e-02
-7.210626507497e-03 8.081198471645e-03 -9.999413164504e-01 -5.403984729748e-02
9.999738645903e-01 4.859485810390e-04 -7.206933692422e-03 -2.921968648686e-01

**Comment by ZikangYuan** [comment]
您好，第一行是相机内参，分别是fx,fy,cx,cy，第二到四行为雷达到相机的外参变换矩阵，前3x3的分块为R，后3x1的分块为t
