### ISSUE TITLE
关于数据集

### ISSUE THREAD

**Issue by James-0911** [ZikangYuan/SDV-LOAM#3]
你好，可以给出你们已经转换好的比如kitti的数据集吗，因为这些数据本身都比较大，可以直接给出链接吗

**Comment by ZikangYuan** [comment]
您好，已经转换好的bag包我们存在本地了，并未上传到云盘上。我们会尽快开始上传，但这需要一些时间。上传完成后，我们会把链接添加进readme里。

**Comment by James-0911** [comment]
> 您好，已经转换好的bag包我们存在本地了，并未上传到云盘上。我们会尽快开始上传，但这需要一些时间。上传完成后，我们会把链接添加进readme里。

好的，非常感谢
