### ISSUE TITLE
roslaunch issue

### ISSUE THREAD

**Issue by Xu-Qingpo** [ZikangYuan/SDV-LOAM#5]
Thank you very much for your contribution！
There is only an interface during the roslaunch process, and nothing happens when playing the .bag file. Can you tell me why? Thanks.

**Comment by ZikangYuan** [comment]
Hi, which datasets are you using?
Perhaps you can check that the topic of data in ROS bag is consistent with that in the config file.

**Comment by ke-cao** [comment]
I met the same problem by using M2DGR. I think the config and topic are correct.

**Comment by ZikangYuan** [comment]
If you use public datasets other than KITTI, Kitti-360, Kitti-Carla, please refer to issue4 to modify the source code.

**Comment by Xu-Qingpo** [comment]
@ZikangYuan Thanks
